apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  name: es-topology-vertical-scaling
  namespace: demo
spec:
  type: VerticalScaling
  databaseRef:
    name: es-topology
  verticalScaling:
    topology:
      master:
        limits:
          cpu: 300m
          memory: 600Mi
        requests:
          cpu: 250m
          memory: 500Mi
      data:
        limits:
          cpu: 350m
          memory: 650Mi
      ingest:
        requests:
          cpu: 400m
          memory: 700Mi
