apiVersion: ops.kubedb.com/v1alpha1
kind: ElasticsearchOpsRequest
metadata:
  name: es-combined-remove-tls
  namespace: demo
spec:
  type: ReconfigureTLS
  databaseRef:
    name: es-combined
  tls:
    remove: true